/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TraceabilityMerkleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ROLE_AUDITOR"
      | "ROLE_PROCESSOR"
      | "ROLE_PRODUCER"
      | "ROLE_RETAILER"
      | "ROLE_TRANSPORTER"
      | "batchCodeHashToBatchId"
      | "batchEvents"
      | "batchMerkleRoot"
      | "batches"
      | "bindBatchCode"
      | "commitBatchMerkleRoot"
      | "createBatch"
      | "createProduct"
      | "eventsById"
      | "getBatch"
      | "getBatchEvents"
      | "hasRole"
      | "nextBatchId"
      | "nextEventId"
      | "nextProductId"
      | "owner"
      | "pause"
      | "paused"
      | "products"
      | "recordTraceEvent"
      | "roles"
      | "setRoles"
      | "transferBatch"
      | "transferOwnership"
      | "unpause"
      | "verifyWithRoot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchCodeBound"
      | "BatchCreated"
      | "BatchMerkleRootCommitted"
      | "OwnershipTransferred"
      | "Paused"
      | "ProductCreated"
      | "RolesUpdated"
      | "TraceEventRecorded"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ROLE_AUDITOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_PROCESSOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_PRODUCER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_RETAILER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_TRANSPORTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchCodeHashToBatchId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchEvents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMerkleRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bindBatchCode",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "commitBatchMerkleRoot",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createBatch",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createProduct",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eventsById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchEvents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBatchId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextEventId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextProductId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTraceEvent",
    values: [BigNumberish, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "roles", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setRoles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferBatch",
    values: [BigNumberish, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyWithRoot",
    values: [BytesLike, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "ROLE_AUDITOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_PROCESSOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_PRODUCER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_RETAILER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROLE_TRANSPORTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCodeHashToBatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bindBatchCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitBatchMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventsById", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBatchEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextBatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEventId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextProductId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTraceEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRoles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyWithRoot",
    data: BytesLike
  ): Result;
}

export namespace BatchCodeBoundEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    batchCodeHash: BytesLike,
    batchCode: string
  ];
  export type OutputTuple = [
    batchId: bigint,
    batchCodeHash: string,
    batchCode: string
  ];
  export interface OutputObject {
    batchId: bigint;
    batchCodeHash: string;
    batchCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchCreatedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    productId: BigNumberish,
    creator: AddressLike,
    initialDataHash: BytesLike
  ];
  export type OutputTuple = [
    batchId: bigint,
    productId: bigint,
    creator: string,
    initialDataHash: string
  ];
  export interface OutputObject {
    batchId: bigint;
    productId: bigint;
    creator: string;
    initialDataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMerkleRootCommittedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    merkleRoot: BytesLike,
    committer: AddressLike
  ];
  export type OutputTuple = [
    batchId: bigint,
    merkleRoot: string,
    committer: string
  ];
  export interface OutputObject {
    batchId: bigint;
    merkleRoot: string;
    committer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductCreatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    owner: AddressLike,
    name: string,
    metadataURI: string
  ];
  export type OutputTuple = [
    productId: bigint,
    owner: string,
    name: string,
    metadataURI: string
  ];
  export interface OutputObject {
    productId: bigint;
    owner: string;
    name: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RolesUpdatedEvent {
  export type InputTuple = [account: AddressLike, roles: BigNumberish];
  export type OutputTuple = [account: string, roles: bigint];
  export interface OutputObject {
    account: string;
    roles: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TraceEventRecordedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    batchId: BigNumberish,
    eventType: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish,
    dataHash: BytesLike
  ];
  export type OutputTuple = [
    eventId: bigint,
    batchId: bigint,
    eventType: bigint,
    actor: string,
    timestamp: bigint,
    dataHash: string
  ];
  export interface OutputObject {
    eventId: bigint;
    batchId: bigint;
    eventType: bigint;
    actor: string;
    timestamp: bigint;
    dataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TraceabilityMerkleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TraceabilityMerkleRegistry;
  waitForDeployment(): Promise<this>;

  interface: TraceabilityMerkleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ROLE_AUDITOR: TypedContractMethod<[], [bigint], "view">;

  ROLE_PROCESSOR: TypedContractMethod<[], [bigint], "view">;

  ROLE_PRODUCER: TypedContractMethod<[], [bigint], "view">;

  ROLE_RETAILER: TypedContractMethod<[], [bigint], "view">;

  ROLE_TRANSPORTER: TypedContractMethod<[], [bigint], "view">;

  batchCodeHashToBatchId: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  batchEvents: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  batchMerkleRoot: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  batches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean, boolean, string] & {
        productId: bigint;
        creator: string;
        currentOwner: string;
        initialDataHash: string;
        exists: boolean;
        closed: boolean;
        pendingReceiver: string;
      }
    ],
    "view"
  >;

  bindBatchCode: TypedContractMethod<
    [batchId: BigNumberish, batchCode: string],
    [void],
    "nonpayable"
  >;

  commitBatchMerkleRoot: TypedContractMethod<
    [batchId: BigNumberish, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  createBatch: TypedContractMethod<
    [productId: BigNumberish, initialDataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  createProduct: TypedContractMethod<
    [name: string, metadataURI: string],
    [bigint],
    "nonpayable"
  >;

  eventsById: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, string] & {
        batchId: bigint;
        eventType: bigint;
        actor: string;
        timestamp: bigint;
        dataHash: string;
      }
    ],
    "view"
  >;

  getBatch: TypedContractMethod<
    [batchId: BigNumberish],
    [
      [bigint, string, string, string, boolean, boolean, string] & {
        productId: bigint;
        creator: string;
        currentOwner: string;
        initialDataHash: string;
        exists: boolean;
        closed: boolean;
        pendingReceiver: string;
      }
    ],
    "view"
  >;

  getBatchEvents: TypedContractMethod<
    [batchId: BigNumberish],
    [bigint[]],
    "view"
  >;

  hasRole: TypedContractMethod<
    [account: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;

  nextBatchId: TypedContractMethod<[], [bigint], "view">;

  nextEventId: TypedContractMethod<[], [bigint], "view">;

  nextProductId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        name: string;
        metadataURI: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  recordTraceEvent: TypedContractMethod<
    [
      batchId: BigNumberish,
      eventType: BigNumberish,
      dataHash: BytesLike,
      receiver: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  roles: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setRoles: TypedContractMethod<
    [account: AddressLike, newRoles: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferBatch: TypedContractMethod<
    [
      batchId: BigNumberish,
      to: AddressLike,
      eventType: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyWithRoot: TypedContractMethod<
    [leaf: BytesLike, root: BytesLike, proof: BytesLike[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ROLE_AUDITOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_PROCESSOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_PRODUCER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_RETAILER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROLE_TRANSPORTER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchCodeHashToBatchId"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchEvents"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchMerkleRoot"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean, boolean, string] & {
        productId: bigint;
        creator: string;
        currentOwner: string;
        initialDataHash: string;
        exists: boolean;
        closed: boolean;
        pendingReceiver: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bindBatchCode"
  ): TypedContractMethod<
    [batchId: BigNumberish, batchCode: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitBatchMerkleRoot"
  ): TypedContractMethod<
    [batchId: BigNumberish, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createBatch"
  ): TypedContractMethod<
    [productId: BigNumberish, initialDataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProduct"
  ): TypedContractMethod<
    [name: string, metadataURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eventsById"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, string] & {
        batchId: bigint;
        eventType: bigint;
        actor: string;
        timestamp: bigint;
        dataHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish],
    [
      [bigint, string, string, string, boolean, boolean, string] & {
        productId: bigint;
        creator: string;
        currentOwner: string;
        initialDataHash: string;
        exists: boolean;
        closed: boolean;
        pendingReceiver: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatchEvents"
  ): TypedContractMethod<[batchId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [account: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextBatchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextEventId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextProductId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        name: string;
        metadataURI: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordTraceEvent"
  ): TypedContractMethod<
    [
      batchId: BigNumberish,
      eventType: BigNumberish,
      dataHash: BytesLike,
      receiver: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roles"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setRoles"
  ): TypedContractMethod<
    [account: AddressLike, newRoles: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferBatch"
  ): TypedContractMethod<
    [
      batchId: BigNumberish,
      to: AddressLike,
      eventType: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyWithRoot"
  ): TypedContractMethod<
    [leaf: BytesLike, root: BytesLike, proof: BytesLike[]],
    [boolean],
    "view"
  >;

  getEvent(
    key: "BatchCodeBound"
  ): TypedContractEvent<
    BatchCodeBoundEvent.InputTuple,
    BatchCodeBoundEvent.OutputTuple,
    BatchCodeBoundEvent.OutputObject
  >;
  getEvent(
    key: "BatchCreated"
  ): TypedContractEvent<
    BatchCreatedEvent.InputTuple,
    BatchCreatedEvent.OutputTuple,
    BatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BatchMerkleRootCommitted"
  ): TypedContractEvent<
    BatchMerkleRootCommittedEvent.InputTuple,
    BatchMerkleRootCommittedEvent.OutputTuple,
    BatchMerkleRootCommittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProductCreated"
  ): TypedContractEvent<
    ProductCreatedEvent.InputTuple,
    ProductCreatedEvent.OutputTuple,
    ProductCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RolesUpdated"
  ): TypedContractEvent<
    RolesUpdatedEvent.InputTuple,
    RolesUpdatedEvent.OutputTuple,
    RolesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TraceEventRecorded"
  ): TypedContractEvent<
    TraceEventRecordedEvent.InputTuple,
    TraceEventRecordedEvent.OutputTuple,
    TraceEventRecordedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BatchCodeBound(uint256,bytes32,string)": TypedContractEvent<
      BatchCodeBoundEvent.InputTuple,
      BatchCodeBoundEvent.OutputTuple,
      BatchCodeBoundEvent.OutputObject
    >;
    BatchCodeBound: TypedContractEvent<
      BatchCodeBoundEvent.InputTuple,
      BatchCodeBoundEvent.OutputTuple,
      BatchCodeBoundEvent.OutputObject
    >;

    "BatchCreated(uint256,uint256,address,bytes32)": TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;
    BatchCreated: TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;

    "BatchMerkleRootCommitted(uint256,bytes32,address)": TypedContractEvent<
      BatchMerkleRootCommittedEvent.InputTuple,
      BatchMerkleRootCommittedEvent.OutputTuple,
      BatchMerkleRootCommittedEvent.OutputObject
    >;
    BatchMerkleRootCommitted: TypedContractEvent<
      BatchMerkleRootCommittedEvent.InputTuple,
      BatchMerkleRootCommittedEvent.OutputTuple,
      BatchMerkleRootCommittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProductCreated(uint256,address,string,string)": TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;
    ProductCreated: TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;

    "RolesUpdated(address,uint256)": TypedContractEvent<
      RolesUpdatedEvent.InputTuple,
      RolesUpdatedEvent.OutputTuple,
      RolesUpdatedEvent.OutputObject
    >;
    RolesUpdated: TypedContractEvent<
      RolesUpdatedEvent.InputTuple,
      RolesUpdatedEvent.OutputTuple,
      RolesUpdatedEvent.OutputObject
    >;

    "TraceEventRecorded(uint256,uint256,uint8,address,uint64,bytes32)": TypedContractEvent<
      TraceEventRecordedEvent.InputTuple,
      TraceEventRecordedEvent.OutputTuple,
      TraceEventRecordedEvent.OutputObject
    >;
    TraceEventRecorded: TypedContractEvent<
      TraceEventRecordedEvent.InputTuple,
      TraceEventRecordedEvent.OutputTuple,
      TraceEventRecordedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
